name: linux

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04, macos-10.14]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
        with:
          submodules: "recursive"
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
    - name: Install libssh
      run: apt install libssh-dev
    - name: Build and test
      run: |
        rustc -V
        cargo -V
        cargo test
        cargo run --example link --features vendored
        cargo run --example link --features vendored,vendored-openssl
